### ISSUE TITLE
Difficultés de configuration

### ISSUE THREAD

**Issue by enadji** [chapitreneuf/pdfgen#7]
Bonjour,

nous rencontrons quelques difficultés à faire fonctionner pdfgen.

- Lodel fonctionne sur une machine virtuelle.
- Le plugin pdfgen est installé.
- Le `docker-compose up` est lancé à partir du dossier du plugin.

Donc Lodel/nginx et Docker sont sur la même machine.

(est-ce nécessaire d’avoir le conteneur sur un autre serveur? Je ne connais rien à Docker…).

Dans le `docker-compose.yml` nous avons renseigné :

- `BASIC_AUTH_USER` et `BASIC_AUTH_PASS`. 
- `PROXY_URL` comme `http://127.0.0.1:3000` (puisque même machine)
- `ports` comme `90:90`. (pour éviter le conflit avec nginx)

En conséquence l’URL de configuration du plugin est sous la forme `http://id:motdepasse@127.0.0.1:90`.

Après lecture de [l’issue 6](https://github.com/edinum/pdfgen/issues/6), nous avons rectifié `thecodingmachine/gotenberg:latest` en `thecodingmachine/gotenberg:6`.

Aurions nous manqué quelque chose ?

**Comment by nahuelange** [comment]
Bonjour,

L'erreur vient probablement de votre modification de PROXY_URL.
Le proxy (container nommé proxy) sert uniquement pour l'authentification, et transmet la requête à l'URL fournie dans la variable d'environnement PROXY_URL.
Variable qui, dans la configuration que nous avons faite, stipule le service exposé par le container nomme "gotenberg". L'hôte qui doit être renseigné est bien "gotenberg".

J'espère que ceci résoudra votre problème. Si cela n'est toujours pas le cas, n'hésitez pas à nous donner un message d'erreur qui pourrait fournir un indice supplémentaire de l'origine du problème.

**Comment by nahuelange** [comment]
Bonjour,

Vous vous trompez dans la configuration de docker-compose : https://docs.docker.com/compose/compose-file/compose-file-v3/#ports

Le conflit sur le port utilisé vient du fait que sur la même machine vous avez déjà un service exposé sur le port 80 (probablement apache, nginx ou un autre service http).
Exposer le proxy sur un autre port est une bonne idée, par contre il faut matcher avec le bon port exposé par le service du container.
Optez à minima une configuration comme ceci : 
```
ports:
    - "90:80"
```

L'erreur côté lodel, vient très probablement du fait qu'il n'arrive pas à se connecter au service.

**Comment by brrd** [comment]
Je ferme ce vieux ticket. N'hésitez pas vous signaler si le problème est toujours d'actualité.
